version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloudpass
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

  nextcloud:
    image: nextcloud:27
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloudpass
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: localhost 127.0.0.1 nextcloud
    volumes:
      - nextcloud_data:/var/www/html

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "supersecretjwt"
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data

volumes:
  db_data:
  nextcloud_data:
  onlyoffice_data:
